### ISSUE TITLE
Internal Server Error when clicking "download directory". 

### ISSUE THREAD

**Issue by lwasser** [ryanlovett/jupyter-tree-download#5]
Hey there @ryanlovett ... if you happen to have time - i just updated our hub to use 1.0.1 of this tool. 0.1.0 works great on our other hub. but when using this new version i get an Internal Server Error page when i attemt to click the button. this happens regardless of whether i select directories or not. 

<img width="409" alt="Screen Shot 2020-08-26 at 5 30 21 PM" src="https://user-images.githubusercontent.com/7649194/91366764-df57d080-e7c1-11ea-9d2c-eb2db6b3de1c.png">
<img width="1067" alt="Screen Shot 2020-08-26 at 5 29 25 PM" src="https://user-images.githubusercontent.com/7649194/91366766-dff06700-e7c1-11ea-9e5f-9e15896479b7.png">

Note that in the old version, the button says "download" not "download directory". (i'm noting that to ensure i have installed things correctly. 

my image is here - https://github.com/earthlab/hub-ops/blob/master/user-images/ea-hub/Dockerfile 

any thoughts on what may be causig this?

i'm pinging my colleagues @nkorinek and @kcranston give i will be out tomorrow. We just started class so i'd like to address this is possible. i'm just not sure where to start! many thanks in advance.

**Comment by ryanlovett** [comment]
I have feeling this is because 1.0.1 uses zip by default now and not tar.gz as before, so if you don't have zip installed in your image it will produce an error. I ran across this when I [deployed on binder](https://github.com/ryanlovett/jupyter-tree-download/blob/master/binder/apt.txt). I suppose I could try to detect executable availability on the fly, though ultimately it'd be good to [let the user choose](https://github.com/ryanlovett/jupyter-tree-download/pull/3#issuecomment-675020239).

Can you try installing zip in your image? Alternatively, just for debugging, you can also manually append `&compression=gzip` to the URL that gets invoked when you click on the button.

**Comment by kcranston** [comment]
Adding `&compression=gzip` to the URL worked. Thanks! Will make sure we have zip in the image.

**Comment by lwasser** [comment]
oh wow -- that's amazing that it was a fairly straight forward fix. thank you @ryanlovett and thank you @kcranston for being so speedy here in testing!! i'll close this for now!!!

**Comment by ryanlovett** [comment]
Thanks for letting me know! I'll update the README to be more clear about this.

**Comment by lwasser** [comment]
awesome!! glad it was atleast helpful for documentation!!!

**Comment by lwasser** [comment]
hey @ryanlovett when you say install zip. do you have an example of what that would look like? would it be something like a 

`RUN sudo apt-get zip` ?
or is this a [python specific tool called zip ](https://pypi.org/project/zip/) 

do you have an example of a container that i could see where it's installed by chance? .if not just answering the above should be enough. many thanks!

**Comment by ryanlovett** [comment]
Yep, the actual zip binary which this extension uses. Something like
```
USER root
RUN apt-get update && apt-get -y install zip
```

Or append zip to some other apt-get install in your Dockerfile.

Alternatively if you want to have tar.gz remain your default without installing zip, you can (from the README) set `c.TreeDownload.compression = "gzip"` in a jupyter_notebook_config.py in one of the config paths from jupyter --paths. i.e. run `jupyter --paths` to see what locations are read, then write the above config line into jupyter_notebook_config.py in one of those paths.

**Comment by lwasser** [comment]
thank you so much, @ryanlovett  i just tested this locally. it works! I really appreciate your help on this. i like the .zip download as a default. it makes a lot of sense for us!

**Comment by ryanlovett** [comment]
Great! 👍
